default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: rails_kadai3_development
test:
  <<: *default
  database: rails_kadai3_test
production:
  <<: *default
  database: rails_kadai3_production
  username: rails_kadai3
  password: <%= ENV['RAILS_KADAI3_DATABASE_PASSWORD'] %>
